name: GitHub metrics
on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches: "master"
jobs:

# The job below generates the images displayed on lowlighter/lowlighter
# You can reuse these steps if you want to have a profile page similar to mine.
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:

      - name: Personal metrics
        uses: sfelli/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "header, repositories"
          plugin_lines: yes
          plugin_music: yes
          plugin_music_playlist: ${{ secrets.MUSIC_PLAYLIST }}
          plugin_music_limit: 2
          plugin_isocalendar: yes
          plugin_topics: yes
          plugin_topics_mode: mastered
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
          plugin_languages_skipped: lowlighter
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris
